name: Build Linux

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the develop branch
  # push:
  #   branches: [ develop ]
  # pull_request:
  #   branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      # ==== OS Specific Dependencies ====
      - name: Depends
        run: |
          # curl -Lo sdcc.tar.bz2 https://github.com/gbdk-2020/gbdk-2020-sdcc/releases/download/sdcc-12539-official/sdcc-snapshot-amd64-unknown-linux2.5-20210711-12539.tar.bz2
          # Use patched sms/gg z80 build:
          curl -Lo sdcc.tar.bz2 https://github.com/gbdk-2020/gbdk-2020-sdcc/releases/download/sdcc-12539-patched/sdcc-amd64-linux2.5-20210711-12539--sms-gg-patched.tar.bz2
          bunzip2 sdcc.tar.bz2
          tar xvf sdcc.tar

      # ==== Build Steps ====
      - name: Check out GBDK-2020
        uses: actions/checkout@v2
        with:
          path: gbdk-2020
          submodules: false

      # ==== Pre-Build: Set environment vars ====
      # Needs to be in a separate step than build so that setting the environment var takes effect
      #
      - name: Pre-Build
        shell: bash
        run: |
          echo "BUILD_PACKAGE_FILENAME=gbdk-2020-Linux-x64.tar.gz" >> $GITHUB_ENV

      # ==== Builds ====
      - name: Build GBDK-2020
        shell: bash
        run: |
          export SDCCDIR=`pwd`/sdcc
          cd gbdk-2020
          make
          # Now build the examples for all platforms
          cd build
          cd gbdk
          cd examples
          make
          cd ..
          cd ..
          cd ..
          cd ..